name: Apply Changes

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  check-tf-vuls:
    name: Check TF Vuls
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform
          soft_fail: true

  apply:
    name: Apply Changes
    runs-on: ubuntu-latest
    needs: check-tf-vuls
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="bucket_name=clc15-zcanassa-terraform"

      - name: Terraform Apply
        run: terraform apply --auto-approve -var="bucket_name=clc15-zcanassa-terraform"
